export default function StaticContent() {
  const memberProfiles = [
    { name: "Ian Ștefan-Cazacu", role: "AI & Development", poster: "/assets/team-ian-profile.jpg", bio: "Hi, I'm Ian. I'm passionate about artificial intelligence, competitive programming, and building practical AI projects. I enjoy solving challenging problems, learning new technologies, and creating intelligent applications that turn ideas into real-world solutions.", instagram: "https://www.instagram.com/thoresdpit/p/DbRTBmOCJwb/" },
    { name: "Maria Borgovan", role: "Robotics & Design", poster: "/assets/team-maria-profile.jpg", bio: "Hi, I'm Maria! I'm passionate about robotics and programming, and love exploring how technology can turn creative ideas into real projects. In my free time, I enjoy graphic design and learning things that help me grow my skills.", instagram: "https://www.instagram.com/thoresdpit/p/DbsnFDSIuki/" },
    { name: "Natasha Oprean", role: "Product & Design", poster: "/assets/team-natasha-profile.jpg", bio: "Hi, I'm Natasha. I joined dpIT Academy to learn how to develop a real product and understand the world better. I enjoy stepping out of my comfort zone, learning new things, and challenging myself. I'm energetic, sociable, open-minded, and determined; I love technology, sports, music, and dance.", instagram: "https://www.instagram.com/thoresdpit/p/DbRUthDCIRk/" },
    { name: "Vlad Rus", role: "Algorithms & Research", poster: "/assets/team-vlad-profile.jpg", bio: "Hello, I'm Vlad. I'm passionate about artificial intelligence, competitive programming, mathematics, and research. I love building cool projects, solving challenging problems, and learning things that help me grow as a developer and as a person.", instagram: "https://www.instagram.com/thoresdpit/p/DbRUBmliB1k/" },
    { name: "Patric Baidoc", role: "Product Development", poster: "/assets/team-patric-profile.jpg", bio: "Hi, I'm Patric. I want to experience building a real tech product from scratch and understand how an IT company works. I'm especially interested in machine learning and artificial intelligence. I also enjoy piano, history, and swimming.", instagram: "https://www.instagram.com/thoresdpit/p/DbRTuxhCGYE/" },
    { name: "Andrei Pop", role: "Computer Science", poster: "/assets/team-andrei-profile.jpg", bio: "Hi, I'm Andrei. I'm passionate about computer science, programming, and computer hardware. I joined dpIT to learn more about technology, improve my skills, and gain experience through projects. I'm curious, determined, and always eager to learn.", instagram: "https://www.instagram.com/thoresdpit/p/DbRTaLtCO9_/" },
  ];
  return (
    <><header className="site-header"><a className="brand" href="#home" aria-label="Thores home"><img src="/assets/thores-logo.jpg" alt="" /><span>THORES</span></a>
    <button className="menu-toggle" aria-label="Open navigation" aria-expanded="false"><span></span><span></span></button>
    <nav className="main-nav" aria-label="Main navigation"><a className="active" href="#home">Home</a><a href="#story">Our Story</a><a href="#team">The Team</a><a href="#project">The Project</a><a href="#journal">Our Journey</a></nav>
  </header>
  <main>
    <section className="hero section-shell" id="home">
      <img className="decor decor-hero-left" src="/assets/botanical-frame-left.png" alt="" /><img className="decor decor-hero-right" src="/assets/botanical-frame-right.png" alt="" /><img className="moon" src="/assets/moon-stars-art.png" alt="" /><img className="breathing-signal" src="/assets/breathing-signal.png" alt="" />
      <div className="hero-copy"><p className="eyebrow">Every breath matters</p><h1>Understand<br />your breathing,<br /><em>know your night.</em></h1><p className="lead">Thores is a student-built prototype exploring how your breathing during sleep can help you understand your patterns and wake up to clearer insights.</p><div className="hero-actions"><a className="button button-dark" href="#film">Coming soon <span>↘</span></a><a className="button button-outline" href="#project">Explore the project <span>↓</span></a></div></div>
      <div className="phone-wrap"><img className="phone-image" src="/assets/app-phone.jpg" alt="Thores sleep insights app shown on a phone" /><p className="hand-note">Every breath<br />matters.</p></div>
      <div className="mountain-band"><img src="/assets/mountain-ridge.png" alt="" /></div>
    </section>
    <section className="story section-shell" id="story"><div className="coming-soon-panel" id="film"><span>Coming soon</span></div><div className="story-copy"><p className="eyebrow">A thoughtful idea, built together</p><h2>Our story<br />in 60 seconds.</h2><span className="short-rule"></span><p>Meet Thores — a team of high school students turning curiosity into a real technology prototype. This is the story of our idea, our journey and the people behind it.</p><a className="text-link" href="#team">Meet the team <span aria-hidden="true">↓</span></a></div></section>
    <section className="project section-shell" id="project"><div className="section-heading"><span></span><img src="/assets/thores-logo.jpg" alt="" /><span></span><p className="eyebrow">Turning breathing data into meaningful insights</p><h2>What Thores does</h2></div><div className="feature-grid">
      <article className="feature-card"><div className="feature-symbol">01</div><h3>Breaths per minute</h3><p>Tracks breathing rate during sleep and helps make patterns easier to understand.</p><div className="mini-wave"></div></article>
      <article className="feature-card"><div className="feature-symbol">02</div><h3>Respiratory score</h3><p>A personalized overview built from your breathing patterns throughout the night.</p><div className="mini-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></article>
      <article className="feature-card"><div className="feature-symbol">03</div><h3>Suspected events</h3><p>Highlights unusual patterns that may point to disrupted breathing during sleep.</p><div className="mini-dots">· · | · · · | · ·</div></article>
    </div></section>
    <section className="steps section-shell"><div className="section-heading compact"><span></span><span></span><p className="eyebrow">From night to insight — in four simple steps</p><h2>How it works</h2></div><ol className="step-grid"><li><span className="step-number">1</span><span className="step-icon">↗</span><h3>Connect your device</h3><p>Pair a compatible wearable or chest patch prototype with the app.</p></li><li><span className="step-number">2</span><span className="step-icon">☾</span><h3>Overnight monitoring</h3><p>We track breathing while you sleep, quietly in the background.</p></li><li><span className="step-number">3</span><span className="step-icon">▥</span><h3>Personalized analysis</h3><p>Our research explores what is typical for you and when patterns change.</p></li><li><span className="step-number">4</span><span className="step-icon">☼</span><h3>Wake up to insights</h3><p>See a clear summary of your breathing rate and overnight patterns.</p></li></ol></section>
    <section className="team section-shell" id="team"><img className="decor team-flourish" src="/assets/botanical-corner-top-left.png" alt="" /><div className="section-heading team-heading"><p className="eyebrow">The people behind Thores</p><h2>Meet the team</h2><p className="hand-note">Six minds.<br />One clear signal.</p></div><div className="team-grid">
      {memberProfiles.map((member, index) => <article className="member-card" key={member.name}><a className="member-poster" href={member.poster} target="_blank" rel="noreferrer" aria-label={`Open ${member.name}'s full profile poster`}><img src={member.poster} alt={`Profile poster for ${member.name}`} /><span>FULL PROFILE <b>↗</b></span><span className="member-index">0{index + 1} / 06</span></a><div className="member-info"><p className="role">{member.role}</p><h3>{member.name}</h3><details className="member-bio"><summary>Read their introduction</summary><p>{member.bio}</p></details><a href={member.instagram} target="_blank" rel="noreferrer">Instagram intro <span aria-hidden="true">↗</span></a></div></article>)}
    </div><p className="team-source">Team introductions adapted from each member’s post on Instagram. <a href="https://www.instagram.com/thoresdpit/" target="_blank" rel="noreferrer">Follow Thores on Instagram ↗</a></p></section>
    <section className="journey section-shell" id="journal"><div className="journey-copy"><p className="eyebrow">Our journey</p><h2>Built at dpIT Academy</h2><p>Thores is taking shape through dpIT Academy, where high school students learn by building real technology projects with support from experienced mentors.</p><a className="button button-outline" href="https://www.instagram.com/thoresdpit/" target="_blank" rel="noreferrer">Follow our journey <span aria-hidden="true">↗</span></a></div><img className="journey-mountains" src="/assets/journey-school.jpg" alt="The dpIT Academy building among trees" /><p className="journey-note">Learn<br />Build<br />Grow<br />Make an impact</p></section>
  </main>
  <footer className="site-footer"><div className="footer-brand"><a className="brand" href="#home"><img src="/assets/thores-logo.jpg" alt="" /><span>THORES</span></a><p>Every breath matters.</p></div><div className="footer-social"><h3>Follow us</h3><a href="https://www.instagram.com/thoresdpit/" target="_blank" rel="noreferrer">Instagram ↗</a></div><p className="copyright">© 2026 Thores.</p></footer>
    </>
  );
}


